config/routes.rb
Rails.application.routes.draw do
  root "categories#index"
  resources :categories, except: [:edit, :update, :destroy]
  resources :stories, except: [:edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :stories, dependent: :destroy

  validates :name, presence: true
end

app/models/story.rb
class Story < ApplicationRecord
  belongs_to :category

  validates :title, presence: true
  validates :content, presence: true
  validates :category, presence: true

  class << self
    def crawl_web_truyen url, category_id
      page = Nokogiri::HTML open(url)
      doc = page.css(".list-content")
      doc.css(".post-title a").map{|a| a["href"]}.compact.uniq.map do |href|
        page_content = Nokogiri::HTML open(href)
        title = page_content.css(".chapter-header h1 a").text
        content = page_content.css("#content p").text
        Story.create! category_id: category_id, title: title, content: content
      end
    end

    def crawl_doctruyencotich url, category_id
      page = Nokogiri::HTML open(url)
      doc = page.css(".archive")
      doc.css(".baiviet a").map{|a| a["href"]}.compact.uniq.map do |href|
        page_content = Nokogiri::HTML open(href)
        title = page_content.css(".single h1").text
        page_content.css(".single h1").remove
        page_content.css(".single .breakdum").remove
        page_content.css(".single .dv").remove
        content = page_content.text
        Story.create! category_id: category_id, title: title, content: content
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
    respond_to do |format|
      format.html
      format.json{render json: {categories: @categories}}
    end
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params
    if @category.save
      redirect_to categories_path
    else
      render :new
    end
  end

  def show
    @category = Category.find_by id: params[:id]
    if @category
      respond_to do |format|
        format.html
        format.json do
          render json: {category: @category.as_json(include: :stories)}
        end
      end
    else
      respond_to do |format|
        format.html{redirect_to categories_path}
        format.json{render status: :not_found}
      end
    end
  end

  private
  def category_params
    params.require(:category).permit :name
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  def index
    @stories = Story.all
  end

  def new
    @categories = Category.all.map{|category| [category.name, category.id]}
    @story = Story.new category_id: params[:category_id]
  end

  def create
    @story = Story.new story_params
    if @story.save
      redirect_to @story
    else
      @categories = Category.all.map{|category| [category.name, category.id]}
      render :new
    end
  end

  def show
    @story = Story.find_by id: params[:id]
    if @story
      respond_to do |format|
        format.html
        format.json do
          render json: {story: @story.as_json(include: :category)}
        end
      end
    else
      respond_to do |format|
        format.html{redirect_to categories_path}
        format.json{render status: :not_found}
      end
    end
  end

  private
  def story_params
    params.require(:story).permit :category_id, :title, :content
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_category.html.erb
<li>
  <%= link_to category.name, category %>
</li>

app/views/categories/index.html.erb
<h1>Categories</h1>
<p>
  <%= link_to "New category", new_category_path %>
</p>
<ul>
  <%= render @categories %>
</ul>

app/views/categories/new.html.erb
<h1>Add new Category</h1>
<%= form_for @category do |f| %>
  <%= render "shared/errors_messages", object: f.object %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <p></p>
  <%= f.submit %>
<% end %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>

<p>
  <%= link_to "New story", new_story_path(category_id: @category.id) %>
</p>

<ul>
  <%= render @category.stories %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Truyen API</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", media: "all",
      "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application",
      "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_errors_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    The form contains <%= pluralize object.errors.count, "error" %>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/stories/_story.html.erb
<li>
  <%= link_to story.title, story %>
</li>

app/views/stories/index.html.erb
<h1>Stories</h1>
<p>
  <%= link_to "New story", new_story_path %>
</p>
<ul>
  <%= render @stories %>
</ul>

app/views/stories/new.html.erb
<h1>Add new Story</h1>
<%= form_for @story do |f| %>
  <%= render "shared/errors_messages", object: f.object %>
  <%= f.label :category %>
  <%= f.select :category_id, @categories %>
  <p></p>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <p></p>
  <%= f.label :content %>
  <%= f.text_area :content %>
  <p></p>
  <%= f.submit %>
<% end %>

app/views/stories/show.html.erb
<h1><%= @story.title %></h1>

<p>
  <%= @story.content %>
</p>